-- Bad Vendor Inventory entries (bad Vendor SKU or empty Vendor ID)
SELECT *
  FROM VENINV
  WHERE VIN_V_ID = 0 OR VIN_VINO like '%@' OR VIN_VINO like '%@%'

 -- Bad AQ SKUs
 SELECT *
  FROM BARCODES
  WHERE BAR_ID = 2 AND BAR_BARCODE NOT LIKE '%@%' AND BAR_BARCODE != ''

-- Empty Primary Vendor
SELECT ITE_INVNO, ITE_BARCODE, ITE_DESCRIPTION, *
  FROM ITEMS JOIN ITPrice ON ITE_INVNO = ITP_INVNO
  WHERE ITP_PVendorID = 0 AND ITE_INVNO IN (
    SELECT VIN_INVNO
      FROM VENINV
    )

-- No Vendor SKU
SELECT ITE_INVNO, ITE_BARCODE, ITE_DESCRIPTION, *
  FROM ITEMS
  WHERE ITE_BARCODE NOT IN ('MFGTAX', 'GENERIC', 'GST') AND ITE_INVNO NOT IN (
    SELECT VIN_INVNO
      FROM VENINV
    )
