/*
 * Selects the lowest numeric Alt. SKU, ignoring Alt. SKUs that are similar to the Primary SKU
 *  e.g. Alt SKU = [Primary SKU]@[VendorID] or vice versa
 *
 * @author: Tommy Goode
 * @copyright: 2015 International Restaurant Distributors, Inc.
 *
 */

SELECT ALT_BARCODES.BAR_INVNO AS SRS_INVNO, ALT_BARCODES.BAR_Site AS SRS_Site, MIN(try_convert(int, ALT_BARCODES.BAR_BARCODE)) AS SRS_SKU
  FROM dbo.BARCODES AS ALT_BARCODES
    LEFT OUTER JOIN dbo.BARCODES AS PRIMARY_BARCODES
	  ON ALT_BARCODES.BAR_INVNO = PRIMARY_BARCODES.BAR_INVNO
	    AND PRIMARY_BARCODES.BAR_ID = 1
		AND PRIMARY_BARCODES.BAR_Site = ALT_BARCODES.BAR_Site
  WHERE (ALT_BARCODES.BAR_ID = 0)
    AND (isnumeric(ALT_BARCODES.BAR_BARCODE) = 1)
	AND try_convert(int, ALT_BARCODES.BAR_BARCODE) IS NOT null
	AND (LEN(ALT_BARCODES.BAR_BARCODE) < 6)
	AND (NOT (PRIMARY_BARCODES.BAR_BARCODE = LEFT(ALT_BARCODES.BAR_BARCODE, LEN(PRIMARY_BARCODES.BAR_BARCODE))))
	AND (NOT (ALT_BARCODES.BAR_BARCODE = LEFT(PRIMARY_BARCODES.BAR_BARCODE, LEN(ALT_BARCODES.BAR_BARCODE))))
	AND (NOT (REPLACE(PRIMARY_BARCODES.BAR_BARCODE, ' ', '') = REPLACE(ALT_BARCODES.BAR_BARCODE, ' ', '')))
  GROUP BY ALT_BARCODES.BAR_INVNO, ALT_BARCODES.BAR_Site
  ORDER BY SRS_SKU desc
